name: CI/CD Personal Website ke VPS

on:
  push:
    branches:
      - main # ganti jika pakai branch lain

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy project to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "." # Semua file project
          target: "/home/admin1/projects/personal-website" # Direktori tujuan di VPS

      - name: Deploy app on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/admin1/projects/personal-website

            echo "🧹 Hentikan container lama jika ada..."
            docker stop personal-website || true
            docker rm personal-website || true

            echo "🧼 Bersihkan image lama..."
            docker image prune -f

            echo "🐳 Build ulang Docker image..."
            docker build -t personal-website .

            echo "🚀 Jalankan container di port 3000..."
            docker run -d --name personal-website --restart always -p 3000:80 personal-website

            echo "✅ Deploy selesai"
